import { CaseRecord } from "@/types";
import { DEMO_DOCUMENT_ID, DEMO_USER_ID } from "./contract";
import { DEMO_LAWYER_ID } from "./lawyers";

export const DEMO_CASE_ID = "case-demo-1";

export const cases: CaseRecord[] = [
  {
    id: DEMO_CASE_ID,
    clientId: DEMO_USER_ID,
    clientName: "أحمد محمد الزعبي",
    lawyerId: DEMO_LAWYER_ID,
    title: "مراجعة عقد إيجار شقة - خلدا، عمّان",
    category: "rental",
    status: "new",
    priority: "medium",
    summaryAr:
      "المستأجر يطلب مراجعة عقد إيجار سنوي بسبب بند غرامة إنهاء مبكر مرتفع (1000 دينار) وبند مسؤولية عن أضرار القوة القاهرة.",
    summaryEn:
      "Tenant requests review of a one-year lease due to a high early-termination penalty (JOD 1,000) and a force-majeure liability clause.",
    clientStoryAr:
      "وقعت عقد إيجار شقة بخلدا قبل أسبوعين. بعد ما حللت العقد بالذكاء الاصطناعي انتبهت إن في بند إذا طلعت قبل نهاية العقد لازم أدفع 1000 دينار وأخسر التأمين كمان. حابب أفهم إذا هالمبلغ منطقي قانونياً وشو خياراتي.",
    clientStoryEn:
      "I signed a lease for an apartment in Khalda two weeks ago. After running it through the AI analyzer, I noticed a clause requiring JOD 1,000 plus loss of the deposit if I leave before the term ends. I'd like to understand if this is legally reasonable and what my options are.",
    opposingParty: "محمد علي الحوراني (المؤجر)",
    relevantClauseIds: ["cl-3", "cl-4"],
    documentIds: [DEMO_DOCUMENT_ID],
    keyDatesAr: ["تاريخ بدء العقد: 2026/09/01", "تاريخ انتهاء العقد: 2027/08/31"],
    keyDatesEn: ["Lease start: 01/09/2026", "Lease end: 31/08/2027"],
    questionsAr: [
      "هل غرامة الإنهاء المبكر (1000 دينار) متناسبة قانونياً؟",
      "هل يمكن الطعن ببند مسؤولية القوة القاهرة؟",
    ],
    questionsEn: [
      "Is the JOD 1,000 early-termination penalty legally proportionate?",
      "Can the force-majeure liability clause be challenged?",
    ],
    suggestedSpecialty: "rental",
    matchScore: 94,
    createdAt: "2026-09-02T08:30:00.000Z",
    updatedAt: "2026-09-02T08:30:00.000Z",
    nextActionAr: "التواصل مع العميل لتحديد موعد استشارة أولية",
    nextActionEn: "Contact client to schedule an initial consultation",
    deadline: "2026-09-20",
  },
  {
    id: "case-demo-2",
    clientId: "user-citizen-2",
    clientName: "سلمى عودة",
    lawyerId: DEMO_LAWYER_ID,
    title: "نزاع إنهاء عقد عمل",
    category: "employment",
    status: "contacted",
    priority: "high",
    summaryAr: "الموظفة تم إنهاء عقدها دون إشعار مسبق وتطلب مراجعة استحقاقاتها القانونية.",
    summaryEn: "Employee's contract was terminated without prior notice; she requests review of her legal entitlements.",
    clientStoryAr: "تم إبلاغي بإنهاء عملي فجأة بدون إشعار مسبق ولا أعرف حقوقي القانونية من ناحية التعويض.",
    clientStoryEn: "I was suddenly informed my employment was terminated without prior notice, and I don't know my legal rights regarding compensation.",
    opposingParty: "شركة النور للتجارة",
    relevantClauseIds: [],
    documentIds: [],
    keyDatesAr: ["تاريخ الإنهاء: 2026/08/25"],
    keyDatesEn: ["Termination date: 25/08/2026"],
    questionsAr: ["ما هي استحقاقاتي القانونية عند الإنهاء دون إشعار؟"],
    questionsEn: ["What are my legal entitlements for termination without notice?"],
    suggestedSpecialty: "employment",
    matchScore: 88,
    createdAt: "2026-08-28T11:00:00.000Z",
    updatedAt: "2026-09-05T09:00:00.000Z",
    nextActionAr: "طلب نسخة من عقد العمل",
    nextActionEn: "Request a copy of the employment contract",
    deadline: "2026-09-18",
  },
  {
    id: "case-demo-3",
    clientId: "user-citizen-3",
    clientName: "فراس ملحس",
    lawyerId: DEMO_LAWYER_ID,
    title: "مراجعة اتفاقية خدمات مستقل",
    category: "commercial",
    status: "reviewing",
    priority: "low",
    summaryAr: "مستقل يطلب مراجعة اتفاقية تقديم خدمات مع شركة قبل التوقيع.",
    summaryEn: "A freelancer requests review of a services agreement with a company before signing.",
    clientStoryAr: "عم يعرضوا علي عقد تقديم خدمات استشارية وحابب أتأكد إن الشروط عادلة قبل ما أوقع.",
    clientStoryEn: "I've been offered a consulting services contract and want to make sure the terms are fair before signing.",
    opposingParty: "شركة الأفق الرقمي",
    relevantClauseIds: [],
    documentIds: [],
    keyDatesAr: [],
    keyDatesEn: [],
    questionsAr: ["هل بند حصرية العمل مقبول قانونياً؟"],
    questionsEn: ["Is the exclusivity clause legally acceptable?"],
    suggestedSpecialty: "commercial",
    matchScore: 76,
    createdAt: "2026-09-08T14:00:00.000Z",
    updatedAt: "2026-09-09T10:00:00.000Z",
    nextActionAr: "مراجعة مسودة العقد المرفقة",
    nextActionEn: "Review the attached draft contract",
  },
  {
    id: "case-demo-4",
    clientId: "user-citizen-4",
    clientName: "دانا حجازين",
    lawyerId: DEMO_LAWYER_ID,
    title: "مطالبة تعويض ضرر ممتلكات",
    category: "civil",
    status: "in_progress",
    priority: "high",
    summaryAr: "مطالبة بتعويض عن أضرار لحقت بالممتلكات بسبب جار المبنى.",
    summaryEn: "Claim for compensation over property damage caused by a neighbor.",
    clientStoryAr: "صار تسرب مياه من شقة الجار وسبب ضرر كبير لأثاث البيت، وحابة أعرف كيف أطالب بالتعويض.",
    clientStoryEn: "A water leak from my neighbor's apartment caused significant damage to my furniture, and I want to know how to claim compensation.",
    opposingParty: "الجار (الطابق العلوي)",
    relevantClauseIds: [],
    documentIds: [],
    keyDatesAr: ["تاريخ الحادثة: 2026/07/14"],
    keyDatesEn: ["Incident date: 14/07/2026"],
    questionsAr: [],
    questionsEn: [],
    suggestedSpecialty: "civil",
    matchScore: 81,
    createdAt: "2026-07-20T09:00:00.000Z",
    updatedAt: "2026-09-01T09:00:00.000Z",
    nextActionAr: "إعداد إنذار عدلي للجار",
    nextActionEn: "Prepare a formal notice to the neighbor",
    deadline: "2026-09-22",
  },
  {
    id: "case-demo-5",
    clientId: "user-citizen-5",
    clientName: "معاذ الشوابكة",
    lawyerId: DEMO_LAWYER_ID,
    title: "قضية إخلاء عقاري",
    category: "real_estate",
    status: "court",
    priority: "urgent",
    summaryAr: "قضية إخلاء أمام محكمة الصلح بسبب تأخر المستأجر عن السداد لثلاثة أشهر.",
    summaryEn: "Eviction case before the magistrate court due to three months of unpaid rent.",
    clientStoryAr: "المستأجر متأخر ثلاثة أشهر عن دفع الأجرة ولا يرد على التواصل، رفعت الدعوى الأسبوع الماضي.",
    clientStoryEn: "The tenant is three months behind on rent and unresponsive; I filed the case last week.",
    opposingParty: "المستأجر",
    relevantClauseIds: [],
    documentIds: [],
    keyDatesAr: ["الجلسة القادمة: 2026/09/28"],
    keyDatesEn: ["Next hearing: 28/09/2026"],
    questionsAr: [],
    questionsEn: [],
    suggestedSpecialty: "real_estate",
    matchScore: 90,
    createdAt: "2026-06-15T09:00:00.000Z",
    updatedAt: "2026-09-10T09:00:00.000Z",
    nextActionAr: "تجهيز المستندات لجلسة المحكمة",
    nextActionEn: "Prepare documents for the court hearing",
    deadline: "2026-09-28",
  },
  {
    id: "case-demo-6",
    clientId: "user-citizen-6",
    clientName: "هبة النسور",
    lawyerId: DEMO_LAWYER_ID,
    title: "استشارة تأسيس شركة ناشئة",
    category: "corporate",
    status: "closed",
    priority: "low",
    summaryAr: "استشارة مكتملة حول الشكل القانوني الأنسب لتأسيس شركة ناشئة.",
    summaryEn: "Completed consultation on the most suitable legal structure for a startup.",
    clientStoryAr: "كنت بحاجة استشارة سريعة لفهم الفرق بين شركة الشخص الواحد وذات المسؤولية المحدودة.",
    clientStoryEn: "I needed a quick consultation to understand the difference between a sole proprietorship and an LLC.",
    opposingParty: undefined,
    relevantClauseIds: [],
    documentIds: [],
    keyDatesAr: [],
    keyDatesEn: [],
    questionsAr: [],
    questionsEn: [],
    suggestedSpecialty: "corporate",
    matchScore: 70,
    createdAt: "2026-05-01T09:00:00.000Z",
    updatedAt: "2026-05-10T09:00:00.000Z",
  },
];

export const getCase = (id: string) => cases.find((c) => c.id === id);
