import { Lawyer, Review } from "@/types";

export const DEMO_LAWYER_ID = "lawyer-demo-1";

export const lawyers: Lawyer[] = [
  {
    id: DEMO_LAWYER_ID,
    profileId: "profile-lawyer-1",
    fullName: "المحامية لينا القاسم",
    specialties: ["rental", "civil", "real_estate"],
    bio: "محامية مختصة بالعقود العقارية وقضايا الإيجارات مع خبرة 9 سنوات في تمثيل المستأجرين والملاك أمام المحاكم الأردنية.",
    city: "عمّان",
    languages: ["ar", "en"],
    consultationPrice: 25,
    availabilityStatus: "available_today",
    consultationTypes: ["video", "in_person", "phone"],
    verificationStatus: "demo_verified",
    yearsExperience: 9,
    rating: 4.8,
    reviewCount: 63,
    completedCases: 214,
    responseTimeHours: 2,
  },
  {
    id: "lawyer-demo-2",
    profileId: "profile-lawyer-2",
    fullName: "المحامي خالد أبو نمر",
    specialties: ["employment", "commercial", "corporate"],
    bio: "متخصص في قانون العمل والشركات، يساعد الموظفين وأصحاب الأعمال في مراجعة العقود وحل النزاعات العمالية.",
    city: "عمّان",
    languages: ["ar", "en"],
    consultationPrice: 30,
    availabilityStatus: "available_this_week",
    consultationTypes: ["video", "in_person"],
    verificationStatus: "demo_verified",
    yearsExperience: 12,
    rating: 4.9,
    reviewCount: 88,
    completedCases: 301,
    responseTimeHours: 4,
  },
  {
    id: "lawyer-demo-3",
    profileId: "profile-lawyer-3",
    fullName: "المحامية رنا الطراونة",
    specialties: ["family", "civil"],
    bio: "تقدّم استشارات قانونية في قضايا الأسرة والأحوال المدنية بأسلوب متفهم وداعم للعملاء.",
    city: "إربد",
    languages: ["ar"],
    consultationPrice: 20,
    availabilityStatus: "available_today",
    consultationTypes: ["phone", "video"],
    verificationStatus: "demo_verified",
    yearsExperience: 6,
    rating: 4.6,
    reviewCount: 41,
    completedCases: 132,
    responseTimeHours: 3,
  },
  {
    id: "lawyer-demo-4",
    profileId: "profile-lawyer-4",
    fullName: "المحامي عمر السعودي",
    specialties: ["criminal", "civil"],
    bio: "خبرة واسعة في القضايا الجزائية والمدنية أمام محاكم الدرجة الأولى والاستئناف.",
    city: "الزرقاء",
    languages: ["ar", "en"],
    consultationPrice: 35,
    availabilityStatus: "busy",
    consultationTypes: ["in_person"],
    verificationStatus: "demo_verified",
    yearsExperience: 15,
    rating: 4.7,
    reviewCount: 97,
    completedCases: 410,
    responseTimeHours: 8,
  },
  {
    id: "lawyer-demo-5",
    profileId: "profile-lawyer-5",
    fullName: "المحامية سارة النابلسي",
    specialties: ["rental", "commercial", "real_estate"],
    bio: "متخصصة في العقود التجارية والعقارية، تساعد الأفراد والشركات الصغيرة في صياغة عقود متوازنة.",
    city: "عمّان",
    languages: ["ar", "en"],
    consultationPrice: 28,
    availabilityStatus: "available_this_week",
    consultationTypes: ["video", "phone"],
    verificationStatus: "demo_verified",
    yearsExperience: 7,
    rating: 4.5,
    reviewCount: 29,
    completedCases: 96,
    responseTimeHours: 5,
  },
  {
    id: "lawyer-demo-6",
    profileId: "profile-lawyer-6",
    fullName: "المحامي يزن الحديد",
    specialties: ["corporate", "commercial"],
    bio: "يقدم استشارات قانونية للشركات الناشئة في التأسيس والعقود والامتثال التنظيمي.",
    city: "عمّان",
    languages: ["en", "ar"],
    consultationPrice: 40,
    availabilityStatus: "available_today",
    consultationTypes: ["video"],
    verificationStatus: "demo_verified",
    yearsExperience: 10,
    rating: 4.9,
    reviewCount: 54,
    completedCases: 178,
    responseTimeHours: 1,
  },
];

export const reviews: Review[] = [
  {
    id: "rev-1",
    lawyerId: DEMO_LAWYER_ID,
    clientName: "أحمد م.",
    rating: 5,
    review: "ساعدتني بفهم عقد الإيجار خلال يوم واحد وكانت واضحة جداً بالشرح.",
    createdAt: "2026-07-12T10:00:00.000Z",
    demo: true,
  },
  {
    id: "rev-2",
    lawyerId: DEMO_LAWYER_ID,
    clientName: "منى س.",
    rating: 5,
    review: "تعاملت باحترافية عالية وتابعت قضيتي حتى النهاية.",
    createdAt: "2026-06-02T10:00:00.000Z",
    demo: true,
  },
  {
    id: "rev-3",
    lawyerId: DEMO_LAWYER_ID,
    clientName: "Yousef K.",
    rating: 4,
    review: "Clear, professional, and responded quickly to my questions.",
    createdAt: "2026-05-20T10:00:00.000Z",
    demo: true,
  },
];

export const getLawyer = (id: string) => lawyers.find((l) => l.id === id);
