import { AppNotification } from "@/types";
import { DEMO_USER_ID } from "./contract";
import { DEMO_LAWYER_ID } from "./lawyers";

export const notifications: AppNotification[] = [
  {
    id: "notif-1",
    userId: DEMO_USER_ID,
    type: "analysis_ready",
    titleAr: "تحليل العقد جاهز",
    titleEn: "Contract analysis ready",
    bodyAr: "انتهينا من تحليل عقد الإيجار الخاص بك. اطلع على النتائج الآن.",
    bodyEn: "We finished analyzing your rental contract. View the results now.",
    read: false,
    createdAt: "2026-09-01T09:05:00.000Z",
    isDemo: true,
    href: "/citizen/analyses",
  },
  {
    id: "notif-2",
    userId: DEMO_USER_ID,
    type: "lawyer_response",
    titleAr: "ردّت عليك المحامية",
    titleEn: "Your lawyer responded",
    bodyAr: "ردّت المحامية لينا القاسم على قضيتك وطلبت موعد استشارة.",
    bodyEn: "Lawyer Lina Al-Qasem responded to your case and requested a consultation.",
    read: false,
    createdAt: "2026-09-03T13:00:00.000Z",
    isDemo: true,
    href: "/citizen/cases",
  },
  {
    id: "notif-3",
    userId: DEMO_USER_ID,
    type: "review_reminder",
    titleAr: "كيف كانت تجربتك؟",
    titleEn: "How was your experience?",
    bodyAr: "مرّت 48 ساعة على استشارتك، شاركنا رأيك بالمحامية.",
    bodyEn: "48 hours have passed since your consultation — share your feedback.",
    read: true,
    createdAt: "2026-09-05T09:00:00.000Z",
    isDemo: true,
  },
  {
    id: "notif-4",
    userId: DEMO_LAWYER_ID,
    type: "case_update",
    titleAr: "قضية جديدة بانتظارك",
    titleEn: "A new case is waiting",
    bodyAr: "وصلتك قضية جديدة من أحمد محمد الزعبي بخصوص عقد إيجار.",
    bodyEn: "A new case arrived from Ahmad Mohammad Al-Zoubi regarding a rental contract.",
    read: false,
    createdAt: "2026-09-02T08:31:00.000Z",
    isDemo: true,
    href: "/lawyer/cases",
  },
  {
    id: "notif-5",
    userId: DEMO_LAWYER_ID,
    type: "appointment",
    titleAr: "موعد استشارة غداً",
    titleEn: "Consultation tomorrow",
    bodyAr: "لديك استشارة فيديو مع أحمد محمد الزعبي غداً الساعة 11:00 صباحاً.",
    bodyEn: "You have a video consultation with Ahmad Al-Zoubi tomorrow at 11:00 AM.",
    read: false,
    createdAt: "2026-09-17T09:00:00.000Z",
    isDemo: true,
    href: "/lawyer/calendar",
  },
];
